# Dictionary of each group from the SEIR point of view
seir-groups:
  young: 
    name: "young"
    # Initial conditions for dynamics
    initial-conditions:
      S: 10
      E: 0
      I: 0
      R: 0
      Ia: 0
      Ips: 0
      Ims: 0
      Iss: 0
      Rq: 0
      H: 0
      ICU: 0
      D: 0

    # Parameters specific to the group
    parameters:
      # Probability of exposition
      beta: 0
      # Rate of infection
      sigma: 0
      # Rate of infection moving to next state (either recovery, hospital bed or ICU)
      mu: 0
      # Prob of moving to hospital bed from infection
      p_H: 0.1
      # Prob of moving to ICU from infection
      p_ICU: 0.1
      # Prob of moving to asymptomatic infection
      p_Ia: 0
      # Prob of moving to ps infection
      p_Ips: 0
      # Prob of moving to ms infection
      p_Ims: 0
      # Prob of moving to ss infection
      p_Iss: 0
      # Rate of recovery from Hospital Bed
      lambda_H_R: 0
      # Rate of recovery from ICU
      lambda_ICU_R: 0
      # Rate of death in Hospital bed
      lambda_H_D: 0
      # Rate of death in ICU
      lambda_ICU_D: 0

    # Number of contacts with other groups
    contacts:
      adult: 2
      young: 2
      old: 2

  adult:
    name: "adult"
    initial-conditions:
      S: 10
      E: 0
      I: 0
      R: 0
      Ia: 0
      Ips: 0
      Ims: 0
      Iss: 0
      Rq: 0
      H: 0
      ICU: 0
      D: 0
    parameters:
      beta: 0
      sigma: 0
      mu: 0
      p_H: 0.1
      p_ICU: 0.1
      p_Ia: 0
      p_Ips: 0
      p_Ims: 0
      p_Iss: 0
      lambda_H_R: 0
      lambda_ICU_R: 0
      lambda_H_D: 0
      lambda_ICU_D: 0

    contacts:
      adult: 2
      young: 2
      old: 2

  old:
    name: "old"
    initial-conditions:
      S: 10
      E: 0
      I: 0
      R: 0
      Ia: 0
      Ips: 0
      Ims: 0
      Iss: 0
      Rq: 0
      H: 0
      ICU: 0
      D: 0
    parameters:
      beta: 0
      sigma: 0
      mu: 0
      p_H: 0.1
      p_ICU: 0.1
      p_Ia: 0
      p_Ips: 0
      p_Ims: 0
      p_Iss: 0
      lambda_H_R: 0
      lambda_ICU_R: 0
      lambda_H_D: 0
      lambda_ICU_D: 0
    contacts:
      adult: 2
      young: 2
      old: 2

# Parameters unspecific to any group
global-parameters:
      # Hospitals capacity
      C_H: 10
      # ICU capacity
      C_ICU: 10
      # Daily antibody tests
      A_tests: 0
      # Daily molecular test
      M_tests: 0