age_group_1:
  0:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 0.0
    transport: 0.0
    work: 0
  1:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 0.5
    transport: 0.5
    work: 1
  2:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 1.0
    transport: 1.0
    work: 1
  3:
    home: 1
    leisure: 0.5
    other: 0.5
    school: 1.0
    transport: 1.0
    work: 1
  4:
    home: 1
    leisure: 1.0
    other: 1.0
    school: 1.0
    transport: 1.0
    work: 1
age_group_2:
  0:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 0.0
    transport: 0.0
    work: 0
  1:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 0.5
    transport: 0.5
    work: 1
  2:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 1.0
    transport: 1.0
    work: 1
  3:
    home: 1
    leisure: 0.5
    other: 0.5
    school: 1.0
    transport: 1.0
    work: 1
  4:
    home: 1
    leisure: 1.0
    other: 1.0
    school: 1.0
    transport: 1.0
    work: 1
age_group_3:
  0:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 0
    transport: 0.0
    work: 0.0
  1:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 1
    transport: 0.5
    work: 0.5
  2:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 1
    transport: 1.0
    work: 1.0
  3:
    home: 1
    leisure: 0.5
    other: 0.5
    school: 1
    transport: 1.0
    work: 1.0
  4:
    home: 1
    leisure: 1.0
    other: 1.0
    school: 1
    transport: 1.0
    work: 1.0
age_group_4:
  0:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 0
    transport: 0.0
    work: 0.0
  1:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 1
    transport: 0.5
    work: 0.5
  2:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 1
    transport: 1.0
    work: 1.0
  3:
    home: 1
    leisure: 0.5
    other: 0.5
    school: 1
    transport: 1.0
    work: 1.0
  4:
    home: 1
    leisure: 1.0
    other: 1.0
    school: 1
    transport: 1.0
    work: 1.0
age_group_5:
  0:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 0
    transport: 0.0
    work: 0.0
  1:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 1
    transport: 0.5
    work: 0.5
  2:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 1
    transport: 1.0
    work: 1.0
  3:
    home: 1
    leisure: 0.5
    other: 0.5
    school: 1
    transport: 1.0
    work: 1.0
  4:
    home: 1
    leisure: 1.0
    other: 1.0
    school: 1
    transport: 1.0
    work: 1.0
age_group_6:
  0:
    home: 1
    leisure: 0.0
    other: 0.0
    school: 0
    transport: 0.0
    work: 0
  1:
    home: 1
    leisure: 0.5
    other: 0.5
    school: 0
    transport: 0.5
    work: 0
  2:
    home: 1
    leisure: 1.0
    other: 1.0
    school: 1
    transport: 1.0
    work: 1
